### ISSUE TITLE
vim.error: Vim(lcd):E344: Can't find directory

### ISSUE THREAD

**Issue by divinites** [jaxbot/github-issues.vim#159]
I've got the following error even after I follow the advices in #117 
```
"gissues/divinites/oauth-mail/issues" [New DIRECTORY]
Error detected while processing function <SNR>115_showGithubIssues:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 219, in showIssueList
  File "<string>", line 235, in printIssueList
vim.error: Vim(lcd):E344: Can't find directory "gissues/divinites/oauth-mail" in cdpath
```

**Comment by divinites** [comment]
Sorry, it seems to be an issue of my vimrc instead of your plugin... issue closed.
